name: Stars Metrics
on:
#  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics-stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: namgyu-youn
          template: classic
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 6
          config_octicon: yes
          config_padding: 0
          config_timezone: Asia/Seoul