name: Notable Contributions Metrics
on:
#  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics-notable.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: namgyu-youn
          template: classic
          base: ""
          plugin_notable: yes
#         plugin_notable_filter: stars:>20
          plugin_notable_from: organization
          plugin_notable_self: yes
          plugin_notable_types: pull_request
          config_octicon: yes
          config_padding: 0
          config_timezone: Asia/Seoul
          config_display: compact
          config_margin: 0
          config_item_spacing: 0