# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: custom_metrics.svg

          # Options
          user: namgyu-youn
          template: classic
          base: activity, community
          config_octicon: yes
          config_timezone: Asia/Seoul
          plugin_calendar_limit: 1
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
